name: End to End Tests

on: [push]
env:
  TAR_PATH: heighliner.tar

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get heighliner
        run: make get-heighliner

      - name: Build Docker image using Make
        run: make local-image

      - name: Save Docker image as a Tarball
        run: docker save kava:local > ${{ env.TAR_PATH }}

      - name: Publish Tarball as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kava-docker-image
          path: ${{ env.TAR_PATH }}

  prepare-e2e-tests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - name: Generate matrix
        id: set-matrix
        run: |
          # Run the command and convert its output to a JSON array
          TESTS=$(cd interchaintest && go test -list . | grep -v "^ok " | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=${TESTS}" >> $GITHUB_OUTPUT

  e2e-tests:
    needs:
      - build-docker
      - prepare-e2e-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # names of `make` commands to run tests
        test: ${{fromJson(needs.prepare-e2e-tests.outputs.matrix)}}
      fail-fast: false

    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - name: checkout chain
        uses: actions/checkout@v4

      - name: Download Tarball Artifact
        uses: actions/download-artifact@v3
        with:
          name: kava-docker-image

      - name: Load Docker Image
        run: docker load -i ${{ env.TAR_PATH }}

      - name: List Docker images
        run: docker images

      - name: Inspect Docker image
        run: docker inspect kava:local

      - name: run test
        run: cd interchaintest && go test -race -v -run ^${{ matrix.test }}$ .
