  e2e-tests:
    needs: build-docker
    runs-on: ubuntu-latest
    strategy:
        matrix:
            # names of `make` commands to run tests
            test: 
              - ictest-conformance
              - ictest-packet-forward
        fail-fast: false

    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
              
      - name: checkout chain
        uses: actions/checkout@v3

      - name: Download Tarball Artifact
        uses: actions/download-artifact@v3
        with:
          name: chain-docker-image

      - name: Load Docker Image
        run: docker image load -i ${{ env.TAR_PATH }}

      - name: run test
        run: make ${{ matrix.test }}